### ISSUE TITLE
woo commerece

### ISSUE THREAD

**Issue by joshp23** [alextselegidis/easyappointments-wordpress-plugin#12]
Is it possible to make this link up with woo commerce so that services are products in woo?

**Comment by alextselegidis** [comment]
I have to check deeper into this one, but it seems possible. 

I will get back here once I have more information, in the meanwhile if someone else has more information on the topic it would be helpful to post them here. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

Although it's been a while since this ticket was submitted, I will comment some updates. 

While integrating woocommerce is possible, it is currently out of the scope of this plugin, which primarily aims to easily connect Easy!Appointments with WordPress. 

I think that Easy!Appointments itself, or another plugin should make it possible to checkout with woocommerce and book an appointment at the same time. 

I'm therefore closing this for now and will consider it when the time comes to integrate with ecommerce platforms. WooCommerce will definitely be one of them. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
