### ISSUE TITLE
Installation and link buttons are not displayed in newer WP versions. 

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments-wordpress-plugin#7]

**Comment by colorfill** [comment]
@alextselegidis - Hi Alex, just to let you know - the issue is with the Route.php file and lack of consistency in naming files (in route.php you refer to min files e.g. style.min.css / plugin.min.js etc. while in reality files in the directories are not minified so: style.css / plugin.js..). Hope that helps!

**Comment by alextselegidis** [comment]
Hi @colorfill , thanks for you message. This is exactly the problem, the minified files should have been there. I'm preparing an updated version that will address these issues. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed in v1.1.0
